/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.developmentality.photo.Pictures;

import java.io.File;
import java.util.logging.Logger;
import net.developmentality.photo.Metadata;
import net.developmentality.photo.PhotoIndexer;
import net.miginfocom.swing.MigLayout;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.ImageUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import scala.collection.immutable.Map;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//net.developmentality.photo.Pictures//Photomosaic//EN",
autostore = false)
public final class PhotomosaicTopComponent extends TopComponent {

    private static PhotomosaicTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";
    private static final String PREFERRED_ID = "PhotomosaicTopComponent";

    private PhotomosaicPanel panel;

    private Map<File, Metadata> photoIndex;

    public PhotomosaicTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(PhotomosaicTopComponent.class, "CTL_PhotomosaicTopComponent"));
        setToolTipText(NbBundle.getMessage(PhotomosaicTopComponent.class, "HINT_PhotomosaicTopComponent"));
//        setIcon(ImageUtilities.loadImage(ICON_PATH, true));
        putClientProperty(TopComponent.PROP_CLOSING_DISABLED, Boolean.TRUE);

        setLayout(new MigLayout("insets 0, fill"));


        photoIndex = createPhotoindex();
        panel = new PhotomosaicPanel(photoIndex);
        
        add(panel, "grow");
    }

    private Map<File, Metadata> createPhotoindex() {
        String indexLoc = "/Users/nicholasdunn/Desktop/photo/Scala-Photomosaic/index.txt";
        System.out.println("Current directory : " + new File(".").getAbsolutePath());
        return PhotoIndexer.loadIndex(new File(indexLoc));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link #findInstance}.
     */
    public static synchronized PhotomosaicTopComponent getDefault() {
        if (instance == null) {
            instance = new PhotomosaicTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the PhotomosaicTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized PhotomosaicTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(PhotomosaicTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof PhotomosaicTopComponent) {
            return (PhotomosaicTopComponent) win;
        }
        Logger.getLogger(PhotomosaicTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID
                + "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    Object readProperties(java.util.Properties p) {
        if (instance == null) {
            instance = this;
        }
        instance.readPropertiesImpl(p);
        return instance;
    }

    private void readPropertiesImpl(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }
}
